springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: bo.edu.ucb.collas_learning.core.ms_cursos.controller
  pathsToMatch: /**
  override-with-generic-response: false 

api:
  common:
    version: 1.0.0
    title: API Product-Composite
    description: Servicio de cursos y certificaciones :)
    termsOfService: https://www.miempresa.com/terminos
    license: Licencia MIT
    licenseUrl: https://opensource.org/licenses/MIT
    externalDocDesc: Documentación en Wiki
    externalDocUrl: https://www.miempresa.com/wiki
    contact:
      name: Soporte Mi Empresa
      url: https://www.miempresa.com/contacto
      email: soporte@miempresa.com

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, Formato inválido de la solicitud. Ver mensaje de respuesta para más información.
    notFound.description: Not found, el id especificado no existe.
    unprocessableEntity.description: Unprocessable entity, no se puede procesar los parametros de entrada. Ver mensaje de respuesta para más información.

  curso:
  get-curso:
    description: Retorna la información del curso en base al id de curso proporcionado.
    notes: |
      # Respuesta exitosa
      Si el id del curso solicitado es encontrado, el método retornará la información del curso.

      # Respuestas con error
      1. Si ningún curso se encontró se devuelve un error **404 - Not Found**
    parameters:
      cursoId: ID del curso a buscar

  create-curso:
    description: Crea un curso.
    notes: |
      # Respuesta exitosa
      Retorna el curso creado.

      # Respuestas con error
      1. Si los datos enviados son inválidos se devuelve un error **400 - Bad Request**

  update-curso:
    description: Actualiza la información del curso.
    notes: |
      # Respuesta exitosa
      Retorna el curso actualizado.

      # Respuestas con error
      1. Si ningún curso se encontró se devuelve un error **404 - Not Found**
      2. Si los datos enviados son inválidos se devuelve un error **400 - Bad Request**
    parameters:
      cursoId: ID del curso a actualizar

  delete-curso:
    description: Elimina el curso en base al id de curso proporcionado.
    notes: |
      # Respuesta exitosa
      Si el id del curso solicitado es encontrado, se elimina el curso.

      # Respuestas con error
      1. Si ningún curso se encontró se devuelve un error **404 - Not Found**
      2. Si el id del curso enviado es inválido se devuelve un error **400 - Bad Request**
    parameters:
      cursoId: ID del curso a eliminar
